
services:

  php:
    build:
      context: ./ 
      dockerfile: Dockerfile
    container_name: crud-php
    restart: always
    volumes:
      - ./crud:/var/www/html:cached 
    networks:
      - lamp-network
    ports:
   
      - "80:80"

  mysql:
    image: mysql:5.7 
    container_name: crud-mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
      - ./crud:/docker-entrypoint-initdb.d 
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: postdba 
      MYSQL_DATABASE: crud 
    networks:
      - lamp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: crud-phpmyadmin
    restart: always
    volumes:
      - /sessions
    ports:
      - "8080:80"
    links:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: postdba
      PMA_HOST: mysql
    networks:
      - lamp-network

networks:
  lamp-network:
    driver: bridge

