#php
services:

  php:
    build:
      context: ./ # Indica onde está o arquivo Dockerfile
      dockerfile: Dockerfile
    container_name: crud-php # Apelido para o container
    restart: always
    volumes:
      - ./crud:/var/www/html:cached # Irá copiar o conteúdo da pasta src para o container
    networks:
      - lamp-network
    ports:
      # Mapear as portas para ficarem visiveis na máquina host
      - "80:80"

  pgadmin:
    image: dpage/pgadmin4
    container_name: crud-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@servidor.com
      PGADMIN_DEFAULT_PASSWORD: postdba
    ports:
      - 8081:80
    depends_on:
      - postgres
    networks:
      - lamp-network

  mysql:
    image: mysql:5.7 # A versão 8.0 está com instabilidades
    container_name: crud-mysql
    restart: always # Por padrão o Docker não reinicia o container, vamos mudar isso.
    volumes:
      - ./mysql:/var/lib/mysql
      - ./crud:/docker-entrypoint-initdb.d 
    ports:
      - "3306:3306" # Mapeei a porta para funcionar no Dbeaver, mas não precisaria.
    environment:
      MYSQL_ROOT_PASSWORD: postdba # Definir senha do usuário root
      MYSQL_DATABASE: crud # Iniciar o container com um banco criado
    networks:
      - lamp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: crud-phpmyadmin
    restart: always
    volumes:
      - /sessions
    ports:
      - "8080:80"
    links:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: postdba
      PMA_HOST: mysql
    networks:
      - lamp-network

networks:
  lamp-network:
    driver: bridge

