services:
  # PARTE DO APACHE + PHP
  php:
    build:
      context: ./ # Indica onde está o Dockerfile
      dockerfile: Dockerfile
    container_name: crud-apache
    restart: always
    volumes:
      - ./deploy-crud:/var/www/html/
    networks:
      - lamp-network
    ports:
      - "80:80"

  # PARTE DO BANCO DE DADOS POSTGRESQL
  postgres:
    image: postgres:12
    container_name: crud-pgsql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postdba
      POSTGRES_DB: crud # nome do banco criado automaticamente
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - lamp-network

  # INTERFACE DO POSTGRES - PGADMIN
  pgadmin:
    image: dpage/pgadmin4
    container_name: crud-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@servidor.com
      PGADMIN_DEFAULT_PASSWORD: postdba
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - lamp-network

  # PARTE DO BANCO DE DADOS MYSQL
  mysql:
    image: mysql:5.7
    container_name: crud-mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
      - ./deploy-crud:/docker-entrypoint-initdb.d 
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: postdba
      MYSQL_DATABASE: crud
    networks:
      - lamp-network

  # INTERFACE DO MYSQL - PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: crud-phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: postdba 
    ports:
      - "8080:80"
    networks:
      - lamp-network

# REDE PERSONALIZADA PARA COMUNICAÇÃO ENTRE OS CONTAINERS
networks:
  lamp-network:
    driver: bridge
